
Kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: assisted-installer
spec:
  taskRef:  custom-openshiftbuild-task
  parameters:
    - name: repository-url
      value: 'https://github.com/openshift/assisted-installer'
    - name: repository-name
      value: 'assisted-installer'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.assisted-installer.ocp'
