
Kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: taskrun-network-metrics-daemon
spec:
  taskRef:  custom-openshiftbuild-task
  parameters:
    - name: repository-url
      value: 'https://github.com/openshift/network-metrics-daemon'
    - name: repository-name
      value: 'network-metrics-daemon'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
