
Kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: taskrun-operator-marketplace
spec:
  taskRef:  custom-openshiftbuild-task
  parameters:
    - name: repository-url
      value: 'https://github.com/operator-framework/operator-marketplace'
    - name: repository-name
      value: 'operator-marketplace'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
