Kind: Task
apiVersion: 0.0.1
metadata:
  name: custom-openshift-build

spec:
  steps:
    - name: git-clone
      description: 'clone relevant repo'
      command: 
        - git
      args:
        - 'clone'
        - '${params.repository-url}'
        - '--progress'
    - name: pwd
      description: 'print working directory'
      workspace: ${params.repository-name}
      command: 
        - pwd
      args:
        - ''
    - name: ls
      workspace: ${params.repository-name}
      description: 'list current directory'
      command: 
        - ls
      args:
        - '-la'
    - name: verify
      workspace: ${params.repository-name}
      description: 'verify'
      command: 
        - make
      args:
        - 'verify'
    - name: unit-test
      workspace: ${params.repository-name}
      description: 'unit test'
      command: 
        - make
      args:
        - 'test'
    - name: build
      workspace: ${params.repository-name}
      description: 'build'
      command: 
        - make
      args:
        - 'build'
    - name: container-build
      workspace: ${params.repository-name}
      description: 'container build'
      command:
        - podman
      args:
        - 'build'
        - '-t'
        - '${params.base-registry}/${params.repository-name}:${params.tag-version}'
        - '-f'
        - '${params.dockerfile}'
    - name: container-push
      workspace: ${params.repository-name}
      description: 'container push'
      command:
        - podman
      args:
        - 'push'
        - '${params.base-registry}/${params.repository-name}:${params.tag-version}'
        - '--tls-verify=false'
        - '--authfile=${params.authfile}'
