
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: okd-payload-pipeline
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/okd-project/okd-payload-pipeline'
    - name: repository-name
      value: 'okd-payload-pipeline'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: ''
