
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: images
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/okd-project/images'
    - name: repository-name
      value: 'images'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'okd-builder.Dockerfile'
