
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: assisted-installer-agent
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/assisted-installer-agent'
    - name: repository-name
      value: 'assisted-installer-agent'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
