
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: oc
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/oc'
    - name: repository-name
      value: 'oc'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/cli-artifacts/Dockerfile.builder.centos9'
