
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: kubernetes-autoscaler
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/kubernetes-autoscaler'
    - name: repository-name
      value: 'kubernetes-autoscaler'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/cluster-autoscaler/Dockerfile.rhel'
