
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: containernetworking-plugins
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/containernetworking-plugins'
    - name: repository-name
      value: 'containernetworking-plugins'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
