
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: csi-node-driver-registrar
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/csi-node-driver-registrar'
    - name: repository-name
      value: 'csi-node-driver-registrar'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
