
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cloud-network-config-controller
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cloud-network-config-controller'
    - name: repository-name
      value: 'cloud-network-config-controller'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
