
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: csi-driver-manila-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/csi-driver-manila-operator'
    - name: repository-name
      value: 'csi-driver-manila-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'build/Dockerfile.openshift'
