
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: configmap-reload
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/configmap-reload'
    - name: repository-name
      value: 'configmap-reload'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
