
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-policy-controller
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-policy-controller'
    - name: repository-name
      value: 'cluster-policy-controller'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel'
