
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: image-registry
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/image-registry'
    - name: repository-name
      value: 'image-registry'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel7'
