
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: builder
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/builder'
    - name: repository-name
      value: 'builder'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel8'
