
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: etcd
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/etcd'
    - name: repository-name
      value: 'etcd'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel'
