
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: external-dns
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/external-dns'
    - name: repository-name
      value: 'external-dns'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
