
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cloud-provider-gcp
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cloud-provider-gcp'
    - name: repository-name
      value: 'cloud-provider-gcp'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'openshift-hack/images/Dockerfile.openshift'
