
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: router
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/router'
    - name: repository-name
      value: 'router'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/router/base/Dockerfile.rhel'
