
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ironic-static-ip-manager
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ironic-static-ip-manager'
    - name: repository-name
      value: 'ironic-static-ip-manager'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
