
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ironic-image
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ironic-image'
    - name: repository-name
      value: 'ironic-image'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.okd'
