
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ironic-hardware-inventory-recorder-image
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ironic-hardware-inventory-recorder-image'
    - name: repository-name
      value: 'ironic-hardware-inventory-recorder-image'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.centos9'
