
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: kubernetes-kube-storage-version-migrator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/kubernetes-kube-storage-version-migrator'
    - name: repository-name
      value: 'kubernetes-kube-storage-version-migrator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/release/Dockerfile'
