
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: route-override-cni
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/route-override-cni'
    - name: repository-name
      value: 'route-override-cni'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
