
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: must-gather
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/must-gather'
    - name: repository-name
      value: 'must-gather'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel7'
