
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: oauth-server
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/oauth-server'
    - name: repository-name
      value: 'oauth-server'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/Dockerfile.rhel'
