
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: installer
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/installer'
    - name: repository-name
      value: 'installer'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/installer/Dockerfile.ci'
