
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: operator-marketplace
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/operator-framework/operator-marketplace'
    - name: repository-name
      value: 'operator-marketplace'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.okd'
