
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ovirt-csi-driver
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ovirt-csi-driver'
    - name: repository-name
      value: 'ovirt-csi-driver'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
