
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-api-provider-openstack
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-api-provider-openstack'
    - name: repository-name
      value: 'cluster-api-provider-openstack'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel'
