
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: prometheus-alertmanager
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/prometheus-alertmanager'
    - name: repository-name
      value: 'prometheus-alertmanager'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
