
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: kubernetes
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/kubernetes'
    - name: repository-name
      value: 'kubernetes'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.centos9'
