
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: route-controller-manager
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/route-controller-manager'
    - name: repository-name
      value: 'route-controller-manager'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: ''
