
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: .
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: ''
    - name: repository-name
      value: '.'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.centos9'
