
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: machine-os-images
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/machine-os-images'
    - name: repository-name
      value: 'machine-os-images'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.centos9'
