
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: origin
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/origin'
    - name: repository-name
      value: 'origin'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/tests/Dockerfile.centos9'
