
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: alibaba-disk-csi-driver-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/alibaba-disk-csi-driver-operator'
    - name: repository-name
      value: 'alibaba-disk-csi-driver-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
