
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: apiserver-network-proxy
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/apiserver-network-proxy'
    - name: repository-name
      value: 'apiserver-network-proxy'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
