
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: aws-pod-identity-webhook
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/aws-pod-identity-webhook'
    - name: repository-name
      value: 'aws-pod-identity-webhook'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel7'
