
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: aws-ebs-csi-driver
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/aws-ebs-csi-driver'
    - name: repository-name
      value: 'aws-ebs-csi-driver'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift.rhel7'
