
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: baremetal-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/baremetal-operator'
    - name: repository-name
      value: 'baremetal-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
