
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cloud-credential-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cloud-credential-operator'
    - name: repository-name
      value: 'cloud-credential-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: ''
