
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cloud-provider-openstack
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cloud-provider-openstack'
    - name: repository-name
      value: 'cloud-provider-openstack'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/cloud-controller-manager/Dockerfile'
