
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-samples-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-samples-operator'
    - name: repository-name
      value: 'cluster-samples-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.okd'
