
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-machine-approver
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-machine-approver'
    - name: repository-name
      value: 'cluster-machine-approver'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel'
