
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-kube-apiserver-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-kube-apiserver-operator'
    - name: repository-name
      value: 'cluster-kube-apiserver-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel7'
