
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-control-plane-machine-set-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-control-plane-machine-set-operator'
    - name: repository-name
      value: 'cluster-control-plane-machine-set-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
