
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: cluster-dns-operator
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/cluster-dns-operator'
    - name: repository-name
      value: 'cluster-dns-operator'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
