
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: console
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/console'
    - name: repository-name
      value: 'console'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
