
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: contour
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/contour'
    - name: repository-name
      value: 'contour'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
