
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: coredns
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/coredns'
    - name: repository-name
      value: 'coredns'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift.rhel7'
