
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: driver-toolkit
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/driver-toolkit'
    - name: repository-name
      value: 'driver-toolkit'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.centos9'
