
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: egress-router-cni
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/egress-router-cni'
    - name: repository-name
      value: 'egress-router-cni'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel8'
