
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: kuryr-kubernetes
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/kuryr-kubernetes'
    - name: repository-name
      value: 'kuryr-kubernetes'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'openshift-kuryr-cni-rhel8.Dockerfile'
