
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: hypershift
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/hypershift'
    - name: repository-name
      value: 'hypershift'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.control-plane'
