
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ibm-vpc-block-csi-driver
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ibm-vpc-block-csi-driver'
    - name: repository-name
      value: 'ibm-vpc-block-csi-driver'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
