
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: k8s-prometheus-adapter
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/k8s-prometheus-adapter'
    - name: repository-name
      value: 'k8s-prometheus-adapter'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
