
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: machine-api-provider-gcp
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/machine-api-provider-gcp'
    - name: repository-name
      value: 'machine-api-provider-gcp'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel'
