
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: multus-networkpolicy
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/multus-networkpolicy'
    - name: repository-name
      value: 'multus-networkpolicy'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.openshift'
