
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: node_exporter
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/node_exporter'
    - name: repository-name
      value: 'node_exporter'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
