
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: oauth-proxy
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/oauth-proxy'
    - name: repository-name
      value: 'oauth-proxy'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
