
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: oc-mirror
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/oc-mirror'
    - name: repository-name
      value: 'oc-mirror'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'images/cli/Dockerfile.ci'
