
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: ovn-kubernetes
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/ovn-kubernetes'
    - name: repository-name
      value: 'ovn-kubernetes'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.microshift'
