
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: prom-label-proxy
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/prom-label-proxy'
    - name: repository-name
      value: 'prom-label-proxy'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.ocp'
