
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: sig-storage-local-static-provisioner
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/sig-storage-local-static-provisioner'
    - name: repository-name
      value: 'sig-storage-local-static-provisioner'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile.rhel7'
