
kind: TaskRun
apiVersion: 0.0.1
metadata:
  name: vsphere-problem-detector
spec:
  taskRef:
    name: custom-openshift-build
  params:
    - name: repository-url
      value: 'https://github.com/openshift/vsphere-problem-detector'
    - name: repository-name
      value: 'vsphere-problem-detector'
    - name: branch
      value: 'master'
    - name: dockerfile
      value: 'Dockerfile'
