Kind: Task
apiVersion: 0.0.1
metadata:
  name: custom-openshiftbuild-task

spec:
  steps:
    - name: git-clone
      description: 'clone relevant repo'
      command: 
        - git
      args:
        - 'clone'
        - '${params.repository-url}'
        - '--progress'
    - name: update-dockerfile-builder
      workspace: ${params.repository-name}
      description: 'update dockerfile builder'
      command:
        - sed 
      args:
        - '-E'
        - '-i'
        - 's/^FROM(.)*builder$/FROM quay.io\/luzuccar\/golang-toolset:dev AS builder/' 
        - '${params.dockerfile}'
    - name: update-dockerfile-base
      workspace: ${params.repository-name}
      description: 'update dockerfile base'
      command:
        - sed 
      args:
        - '-E'
        - '-i'
        - 's/^FROM(.)*base$/FROM quay.io\/luzuccar\/base:latest/'
        - '${params.dockerfile}'
    - name: container-build
      workspace: ${params.repository-name}
      description: 'container build'
      command:
        - podman
      args:
        - 'build'
        - '-t'
        - '${params.base-registry}/${params.repository-name}:${params.tag-version}'
        - '-f'
        - '${params.dockerfile}'
    - name: container-push
      workspace: ${params.repository-name}
      description: 'container push'
      command:
        - podman
      args:
        - 'push'
        - '${params.base-registry}/${params.repository-name}:${params.tag-version}'
        - '--tls-verify=false'
        #- '--authfile=/home/lzuccarelli/.docker/config.json'
